### ISSUE TITLE
Incorrect rendering of a concept network with multiple hypercubes

### ISSUE THREAD

**Issue by joshuanario** [ecksbee/telefacts#92]
<img width="1695" alt="Screen Shot 2024-01-18 at 7 44 31 PM" src="https://github.com/ecksbee/telefacts/assets/16855011/d20dda97-7529-4805-a93b-46453723539d">

https://edgarbrowser.com/review/?path=%2FArchives%2Fedgar%2Fdata%2F1445305%2F000144530523000042%2F0001445305-23-000042-index.htm

**Comment by SpencerDawson** [comment]
view-source:https://www.sec.gov/Archives/edgar/data/1445305/000144530523000042/wk-20221231_def.xml
Under `IncomeTaxesNarrativeDetails`
See: `OperatingLossCarryforwardsLineItems` and ` TaxCreditCarryforwardLineItems`, referenced in view-source:https://xbrl.fasb.org/us-gaap/2022/elts/us-gaap-2022.xsd.

When visiting said link, and navigating to `IncomeTaxesNarrativeDetails`, under definitions, the resulting items are missing or wrong.

`OperatingLossCarryforwardsLineItems` should have a child, `OperatingLossCarryforwards`.
`TaxCreditCarryforwardLineItems` has the wrong child (`OperatingLossCarryforwards`), should be `TaxCreditCarryforwardAmount`
